In [63]:
import torch
import pandas as pd
import numpy as np
from numpy.linalg import inv
from sklearn.linear_model import LinearRegression

In [81]:
ip_data = pd.read_csv("./qn2_data.csv", header=None)
data = ip_data.values
(X, y) = (data[:, [0,1]], data[:, 2])

In [82]:
def append1(X):
    '''
    Add 1 to the input for to get bias
    '''
    X = np.hstack((X, np.ones((X.shape[0], 1))))
    return X

#### Get parameters with normal equations:

In [83]:
X = append1(X)
Xt = X.T
params = np.dot(np.dot(inv(np.dot(Xt, X)), Xt), y)

# predict output for given data
test_data = append1(np.array([[6,4], [10,5], [14,8]]))
np.dot(test_data, params)

array([ 40.32044761,  44.03051882,  49.96032553])

#### Cross check  with sklean output :

In [84]:
reg = LinearRegression().fit(ip_data.iloc[:, [0,1]], ip_data.iloc[:, 2])

#### Weights and bias for linear fit:

In [85]:
reg.coef_, reg.intercept_

(array([ 0.65005086,  1.10986775]), 31.980671414038671)

#### Predict for the test data:

In [86]:
test_data = np.array([[6,4], [10,5], [14,8]])
reg.predict(test_data)

array([ 40.32044761,  44.03051882,  49.96032553])