In [3]:
import torch

### 1.a 

<h4><i> 3 types of expressions to slice a tensor </i> </h4>

In [10]:
t = torch.Tensor([[1,2,3],[4,5,6],[7,8,9]])

slice1 = t[:, 1]
print(slice1)

slice2_mask = torch.tensor([[0,1,0],[0,1,0],[0,1,0]] , dtype=torch.uint8)
slice2 = torch.masked_select(t, slice2_mask)
print(slice2)

slice3 = t.narrow(1, 1, 1).view([3])
print(slice3)

tensor([2., 5., 8.])
tensor([2., 5., 8.])
tensor([2., 5., 8.])


torch.Size([3])

### 1.b 

<h4> Tensor : </h4>
<p>
    In pytorch library Tensor represents a multi dimensional matrix formulation of single data type. There are different types of Tensors that can be created in CPU and GPU in pytorch.
</p>

<hr/>

<h4> Storage : </h4>
<p>
    torch.Storage represents abstract form of the data in pytorch, so this represents the raw data associated with Tensors and Variables. Every Tensor and Variable will have a Storage associated with them with single data type.
</p>

<h4> Variable: </h4>
<p>
    Till PyTorch0.4.0, to get the auto gradients on operations performed a Storage, we need to store that as Variable. When we call .backward() the gradients will be computed using chain rule till the leaf Variable encountered. But with new versions, Variable is deprecated and we can do autograd operations with Tensors too
</p>